# reproducibility
seed: 42

only_test: False

ckpt_path: null

# pl_trainer
pl_trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  num_nodes: 1
  strategy: auto
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  val_check_interval: 1.0 # you can specify an int "n" here => validation every "n" steps
  check_val_every_n_epoch: 1
  max_epochs: 10
  max_steps: null
  deterministic: True
  fast_dev_run: False
  precision: 16
  # ckpt_path: null

# early stopping callback
#early_stopping_callback: null
early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_loss
  mode: min
  patience: 5

# model_checkpoint_callback
# "model_checkpoint_callback: null" will disable model checkpointing
model_checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss@${train.top_k}
  mode: min
  verbose: True
  save_top_k: 1
  save_last: False
  filename: "checkpoint-val_loss_{val_loss:.4f}-epoch_{epoch:02d}"
  auto_insert_metric_name: False

prediction_callbacks: null
# here you can specify a list of callbacks that will be called after each validation epoch