# Required to make the "experiments" dir the default one for the output of the models
hydra:
  run:
    dir: ./experiments/${model_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

model_name: ${model.language_model}   # used to name the model in wandb
project_name: nlp-template            # used to name the project in wandb

defaults:
  - _self_
  - train: default_train
  - model: default_model
  - data: default_data
  - scheduler: linear_scheduler_with_warmup
  - optimizer: radam
  - loss: crossentropy
  - evaluation: default_evaluation
  - logging: wandb_logging
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
