language_model: "sentence-transformers/all-MiniLM-L12-v2"

pl_module:
  _target_: src.models.pl_modules.PLModule
  model:
    _target_: src.models.model.BaseModel
    loss_fn: ${loss}
  optimizer: ${optimizer}
  lr_scheduler: ${scheduler}
  grouped_parameters: True
  warmup_steps_ratio: 0.1
